/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FestivalsRouteImport } from './routes/festivals'
import { Route as PanchangRouteImport } from './routes/panchang'
import { Route as PoojasRouteImport } from './routes/poojas'
import { Route as PriestEnrolmentRouteImport } from './routes/priest-enrolment'
import { Route as PriestsRouteImport } from './routes/priests'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsRoute = FestivalsRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchangRoute = PanchangRouteImport.update({
  id: '/panchang',
  path: '/panchang',
  getParentRoute: () => rootRouteImport,
} as any)
const PoojasRoute = PoojasRouteImport.update({
  id: '/poojas',
  path: '/poojas',
  getParentRoute: () => rootRouteImport,
} as any)
const PriestEnrolmentRoute = PriestEnrolmentRouteImport.update({
  id: '/priest-enrolment',
  path: '/priest-enrolment',
  getParentRoute: () => rootRouteImport,
} as any)
const PriestsRoute = PriestsRouteImport.update({
  id: '/priests',
  path: '/priests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/festivals': typeof FestivalsRoute
  '/panchang': typeof PanchangRoute
  '/poojas': typeof PoojasRoute
  '/priest-enrolment': typeof PriestEnrolmentRoute
  '/priests': typeof PriestsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/festivals': typeof FestivalsRoute
  '/panchang': typeof PanchangRoute
  '/poojas': typeof PoojasRoute
  '/priest-enrolment': typeof PriestEnrolmentRoute
  '/priests': typeof PriestsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/festivals': typeof FestivalsRoute
  '/panchang': typeof PanchangRoute
  '/poojas': typeof PoojasRoute
  '/priest-enrolment': typeof PriestEnrolmentRoute
  '/priests': typeof PriestsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/contact'
    | '/festivals'
    | '/panchang'
    | '/poojas'
    | '/priest-enrolment'
    | '/priests'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/contact'
    | '/festivals'
    | '/panchang'
    | '/poojas'
    | '/priest-enrolment'
    | '/priests'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/contact'
    | '/festivals'
    | '/panchang'
    | '/poojas'
    | '/priest-enrolment'
    | '/priests'
    | '/_authenticated/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  FestivalsRoute: typeof FestivalsRoute
  PanchangRoute: typeof PanchangRoute
  PoojasRoute: typeof PoojasRoute
  PriestEnrolmentRoute: typeof PriestEnrolmentRoute
  PriestsRoute: typeof PriestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals': {
      id: '/festivals'
      path: '/festivals'
      fullPath: '/festivals'
      preLoaderRoute: typeof FestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchang': {
      id: '/panchang'
      path: '/panchang'
      fullPath: '/panchang'
      preLoaderRoute: typeof PanchangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poojas': {
      id: '/poojas'
      path: '/poojas'
      fullPath: '/poojas'
      preLoaderRoute: typeof PoojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priest-enrolment': {
      id: '/priest-enrolment'
      path: '/priest-enrolment'
      fullPath: '/priest-enrolment'
      preLoaderRoute: typeof PriestEnrolmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priests': {
      id: '/priests'
      path: '/priests'
      fullPath: '/priests'
      preLoaderRoute: typeof PriestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  FestivalsRoute: FestivalsRoute,
  PanchangRoute: PanchangRoute,
  PoojasRoute: PoojasRoute,
  PriestEnrolmentRoute: PriestEnrolmentRoute,
  PriestsRoute: PriestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
