// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Local in-memory datastore (used when Supabase env vars are missing or
// when VITE_USE_LOCAL_STORE=true). This provides sample data and demo auth
// accounts for local development without a Supabase instance.
const USE_LOCAL =
  (import.meta.env?.VITE_USE_LOCAL_STORE === 'true') ||
  !(import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL']);

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    // If local store requested, fall through to create a local client below.
    if (!USE_LOCAL) {
      // In browser/dev, return a no-op client so the app can render without crashing.
      if (typeof window !== 'undefined') {
        const noop = () => ({ data: null, error: null });
        const noOpClient: any = {
          auth: {
            getSession: async () => ({ data: { session: null } }),
            getUser: async () => ({ data: { user: null } }),
            signOut: async () => ({ error: null }),
            signInWithPassword: async () => ({ error: { message: 'Supabase not configured' } }),
            signUp: async () => ({ error: { message: 'Supabase not configured' } }),
            onAuthStateChange: () => ({ subscription: { unsubscribe: () => {} } }),
          },
          from: () => ({ select: async () => ({ data: [], error: null }), update: async () => ({ data: null, error: null }), insert: async () => ({ data: null, error: null }) }),
        };
        return noOpClient as ReturnType<typeof createSupabaseClient>;
      }
      throw new Error(message);
    }
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

// ---------- Local in-memory store implementation ----------
function createLocalClient() {
  type Row = Record<string, any>;

  // Seed data roughly matching migrations
  const users: Row[] = [
    { id: 'u-admin', email: 'admin@aura.test', full_name: 'Admin', password: 'password', role: 'admin' },
    { id: 'u-ravi', email: 'ravi@aura.test', full_name: 'Pandit Ravi Sharma', password: 'password', role: 'priest' },
    { id: 'u-devotee', email: 'devotee@aura.test', full_name: 'Devotee', password: 'password', role: 'customer' },
  ];

  const poojas: Row[] = [
    { id: 'p1', slug: 'ganesha-pooja', name: 'Ganesha Pooja', sanskrit_name: 'गणेश पूजा', category: 'pooja', description: 'Invoke Vighnaharta before any new beginning — home, business or vehicle.', duration_minutes: 60, base_price: 2100, items_price: 900, active: true },
    { id: 'p2', slug: 'satyanarayana-pooja', name: 'Satyanarayana Pooja', sanskrit_name: 'सत्यनारायण पूजा', category: 'pooja', description: 'The classic full-moon katha and pooja for prosperity and gratitude.', duration_minutes: 120, base_price: 3100, items_price: 1400, active: true },
    { id: 'p3', slug: 'griha-pravesh', name: 'Griha Pravesh', sanskrit_name: 'गृह प्रवेश', category: 'pooja', description: 'House-warming vidhi with kalash sthapana and vastu shanti.', duration_minutes: 150, base_price: 3500, items_price: 1800, active: true },
    { id: 'p4', slug: 'navagraha-homa', name: 'Navagraha Homa', sanskrit_name: 'नवग्रह होम', category: 'homa', description: 'Fire ceremony to balance the nine planetary influences in your chart.', duration_minutes: 180, base_price: 6800, items_price: 2600, active: true },
    { id: 'p5', slug: 'ayushya-homa', name: 'Ayushya Homa', sanskrit_name: 'आयुष्य होम', category: 'homa', description: 'Birthday homa performed for long life, health and vitality.', duration_minutes: 120, base_price: 5200, items_price: 2100, active: true },
    { id: 'p6', slug: 'online-consultation', name: 'Online Consultation', sanskrit_name: 'परामर्श', category: 'consultation', description: 'A 30-minute video consultation with a Vedic scholar on muhurta, remedies and rituals.', duration_minutes: 30, base_price: 600, items_price: 0, active: true },
  ];

  const priests: Row[] = [
    {
      id: '11111111-1111-4111-8111-111111111111',
      full_name: 'Pandit Ravi Sharma',
      photo_key: 'p1',
      user_id: 'u-ravi',
      status: 'approved',
      city: 'Bengaluru',
      title: 'Purohit',
      bio: 'Experienced priest specialising in Vedic rituals and family ceremonies.',
      experience_years: 12,
      languages: ['Sanskrit', 'Hindi', 'English'],
      specialities: ['Griha Pravesh', 'Satyanarayana', 'Ganesha Pooja'],
      rating: 4.8,
      reviews_count: 58,
    },
    {
      id: '22222222-2222-4222-8222-222222222222',
      full_name: 'Acharya Suresh Gowda',
      photo_key: 'p2',
      user_id: null,
      status: 'approved',
      city: 'Bengaluru',
      title: 'Acharya',
      bio: 'Specialist in temple ceremonies and astrology-aligned rituals.',
      experience_years: 20,
      languages: ['Kannada', 'Sanskrit', 'English'],
      specialities: ['Temple Pooja', 'Vedic Homam'],
      rating: 4.6,
      reviews_count: 31,
    },
  ];

  const gallery_items: Row[] = [
    { id: 'g1', image_key: 'g1', title: 'Rangoli yantra at dusk', sort_order: 1 },
  ];

  // Platform settings
  const platform_settings: Row[] = [
    { key: 'discovery_radius_km', value: 15 },
    { key: 'whatsapp_enabled', value: true },
  ];

  // Generate panchang for a range of dates (CURRENT_DATE -2 .. +45)
  const panchang: Row[] = [];
  const now = new Date();
  for (let i = -2; i <= 45; i++) {
    const d = new Date(now);
    d.setDate(d.getDate() + i);
    const iso = d.toISOString().slice(0, 10);
    panchang.push({
      panchang_date: iso,
      tithi: `Tithi ${((i + 304) % 15) + 1}`,
      nakshatra: `Nakshatra ${((i + 302) % 9) + 1}`,
      yoga: `Yoga ${((i + 301) % 7) + 1}`,
      karana: `Karana ${((i + 301) % 6) + 1}`,
      vara: d.toLocaleDateString('en-IN', { weekday: 'long' }),
      sunrise: '06:20',
      sunset: '18:35',
      rahu_kaal: '10:30 – 12:00',
      abhijit_muhurat: '12:14 – 12:58',
      auspicious_windows: [
        { label: 'Brahma Muhurat', time: '04:42 – 05:30' },
        { label: 'Abhijit', time: '12:14 – 12:58' },
      ],
      is_auspicious: ((i + 301) % 9) !== 3,
    });
  }

  const festivals: Row[] = [
    { id: 'f1', name: 'Ganesh Chaturthi', festival_date: new Date(now.getTime() + 12 * 24 * 3600 * 1000).toISOString().slice(0, 10), description: 'Arrival of Vighnaharta', suggested_pooja: 'ganesha-pooja' },
  ];

  const priest_availability: Row[] = [];
  for (const p of priests) {
    for (let j = 0; j < 30; j++) {
      const d = new Date(now);
      d.setDate(d.getDate() + j);
      priest_availability.push({ id: `${p.id}-${j}`, priest_id: p.id, available_date: d.toISOString().slice(0, 10) });
    }
  }

  // In-memory session
  let currentSession: { access_token: string | null; user?: any } = { access_token: null, user: null };
  const authSubscribers: Array<(event: string, session: any) => void> = [];

  function emitAuth(event: string, session: any) {
    for (const s of authSubscribers) s(event, session);
  }

  // Generic local query builder with thenable behavior
  function tableFor(name: string): Row[] {
    switch (name) {
      case 'poojas': return poojas;
      case 'priests': return priests;
      case 'gallery_items': return gallery_items;
      case 'panchang': return panchang;
      case 'festivals': return festivals;
      case 'priest_availability': return priest_availability;
      case 'platform_settings': return platform_settings;
      case 'users': return users;
      default:
        return [];
    }
  }

  class LocalQueryBuilder {
    name: string;
    _filters: Array<(r: Row) => boolean> = [];
    _orderField?: string;
    _ascending = true;
    _limit?: number;
    _action: 'select'|'insert'|'update' = 'select';
    _patch: Row | null = null;
    _insertPayload: Row | Row[] | null = null;
    _maybeSingle = false;
    constructor(name: string) { this.name = name; }
    select(_sel?: string) { this._action = 'select'; return this; }
    maybeSingle() { this._maybeSingle = true; return this; }
    eq(field: string, value: any) { this._filters.push((r) => r[field] === value); return this; }
    gte(field: string, value: any) { this._filters.push((r) => r[field] >= value); return this; }
    order(field: string, opts?: { ascending?: boolean }) { this._orderField = field; this._ascending = opts?.ascending ?? true; return this; }
    limit(n: number) { this._limit = n; return this; }
    insert(payload: Row | Row[]) { this._action = 'insert'; this._insertPayload = payload; return this; }
    update(patch: Row) { this._action = 'update'; this._patch = patch; return this; }
    then(resolve: (value: any) => void, reject?: (err: any) => void) {
      try {
        const table = tableFor(this.name);
        if (this._action === 'select') {
          let rows = table.slice();
          for (const f of this._filters) rows = rows.filter(f);
          if (this._orderField) rows.sort((a,b) => {
            if (a[this._orderField!] < b[this._orderField!]) return this._ascending ? -1 : 1;
            if (a[this._orderField!] > b[this._orderField!]) return this._ascending ? 1 : -1;
            return 0;
          });
          if (this._limit != null) rows = rows.slice(0, this._limit);
          if (this._maybeSingle) {
            const res = rows.length > 0 ? rows[0] : null;
            resolve({ data: res, error: null });
          } else {
            resolve({ data: rows, error: null });
          }
          return;
        }
        if (this._action === 'insert') {
          const payload = this._insertPayload;
          if (Array.isArray(payload)) {
            for (const p of payload) table.push(p);
          } else if (payload) {
            table.push(payload);
          }
          resolve({ data: payload, error: null });
          return;
        }
        if (this._action === 'update') {
          let count = 0;
          for (let i = 0; i < table.length; i++) {
            const row = table[i];
            if (this._filters.every((f) => f(row))) {
              table[i] = { ...row, ...(this._patch ?? {}) };
              count++;
            }
          }
          resolve({ data: count > 0 ? table.filter((r) => this._filters.every((f) => f(r))) : null, error: null });
          return;
        }
        resolve({ data: null, error: null });
      } catch (err) {
        reject?.(err);
      }
    }
  }

  const localClient: any = {
    from(name: string) { return new LocalQueryBuilder(name); },
    auth: {
      async getSession() { return { data: { session: currentSession } }; },
      async getUser() { return { data: { user: currentSession.user ?? null } }; },
      async signOut() { currentSession = { access_token: null, user: null }; emitAuth('SIGNED_OUT', currentSession); return { error: null }; },
      async signInWithPassword({ email, password }: { email: string; password: string }) {
        const user = users.find((u) => u.email === email && u.password === password);
        if (!user) return { error: { message: 'Invalid email or password' } };
        currentSession = { access_token: `local-token:${user.email}`, user: { id: user.id, email: user.email, full_name: user.full_name } };
        emitAuth('SIGNED_IN', currentSession);
        return { data: { user: currentSession.user }, error: null };
      },
      async signUp({ email, password, options }: any) {
        if (users.find((u) => u.email === email)) return { error: { message: 'User already exists' } };
        const id = `u-${Math.random().toString(36).slice(2, 9)}`;
        const user = { id, email, password, full_name: options?.data?.full_name ?? email.split('@')[0] };
        users.push(user);
        currentSession = { access_token: `local-token:${user.email}`, user: { id: user.id, email: user.email, full_name: user.full_name } };
        emitAuth('SIGNED_IN', currentSession);
        return { data: { user: currentSession.user }, error: null };
      },
      onAuthStateChange(cb: (event: string, session: any) => void) {
        authSubscribers.push(cb);
        return { subscription: { unsubscribe: () => {
          const idx = authSubscribers.indexOf(cb); if (idx >= 0) authSubscribers.splice(idx, 1);
        } } };
      },
    },
  };

  return localClient as ReturnType<typeof createSupabaseClient>;
}


let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      if (USE_LOCAL) {
        // Use local in-memory client
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        _supabase = createLocalClient();
      } else {
        _supabase = createSupabaseClient();
      }
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
